feat: "undefined" pixels value and "undefined" keyword exact match
Spectoda/spectoda-js pull request #3
Opened 2023-07-06 13:43 UTC by Sebight

2023-07-08 10:14 UTC, immakermatty requested changes
this.#tnglWriter.writeUint16(TNGL_FLAGS.NONE); nedává smysl. Co když někdo TNGL_FLAGS.NONE změní na 1? Pak pixel value 1 bude undefined. 

jestli chceme undefinedpx tak se domu musí udělat zvláštní FLAG neco ala TNGL_FLAGS.UNDEFINED_PIXELS.

Ale možná jsem spíš pro aby bylo jen undefined. Tzn udělat FLAG_UNDEFINED pokud ještě neexistuje. Tzn že decoder když vidí, že na místě, kde je normálně FLAG_PIXELS je FLAG_UNDEFINED, tak nahodí defaultní pixely

2023-07-08 10:14 UTC, immakermatty commented on SpectodaParser.js
> +      this.#tnglWriter.writeUint16(TNGL_FLAGS.NONE);
this.#tnglWriter.writeUint16(TNGL_FLAGS.NONE); nedává smysl. Co když někdo TNGL_FLAGS.NONE změní na 1? Pak pixel value 1 bude undefined. 

jestli chceme undefinedpx tak se domu musí udělat zvláštní FLAG neco ala TNGL_FLAGS.UNDEFINED_PIXELS.

Ale možná jsem spíš pro aby bylo jen undefined. Tzn udělat FLAG_UNDEFINED pokud ještě neexistuje. Tzn že decoder když vidí, že na místě, kde je normálně FLAG_PIXELS je FLAG_UNDEFINED, tak nahodí defaultní pixely

2023-07-08 10:28 UTC, Sebight commented on SpectodaParser.js
> +      this.#tnglWriter.writeUint16(TNGL_FLAGS.NONE);
Ok, to dává smysl. Upravím

2024-02-16 09:41 UTC, sirluky commented
Seems old, closing.

2024-02-16 09:41 UTC, closed without merging