0.9 dev 3774 reconnection
Spectoda/spectoda-js pull request #5
Opened 2024-02-14 20:04 UTC by immakermatty

This branch focuses on optimizing the way the App connects to an installation. But also makes some code refactors and cleanups.

2024-02-15 15:32 UTC, sirluky requested changes

2024-02-15 15:32 UTC, sirluky commented on SpectodaWebSerialConnector.js
> +    if (timeout === CONNECTOR_DEFAULT_VALUE) { timeout = 10000; }
Nejsem si jistej jestli takto setovaný chytaný timeouty dávají smysl.
Když už jsem fanda connect(timeout = 10000) nebo connect(timeout = CONNECTOR_DEFAULT_VALUE)

2024-02-15 15:32 UTC, sirluky commented on SpectodaInterfaceLegacy.js
> +export const CONNECTOR_DEFAULT_VALUE = null;
Název konstanty by mohl být explicitnější že jde o TIMEOUT a děsí mě že je null.

2024-02-16 08:19 UTC, mchlkucera commented on SpectodaWebSerialConnector.js
> +    if (timeout === CONNECTOR_DEFAULT_VALUE) { timeout = 10000; }
Když timeout se rovná "defaultní hodnotě konektoru" tak nastav timeout na číslo 10000? To je za mě dost confusing code. Navíc koukám že CONNECTOR_DEFAULT_VALUE ani neexistuje?

2024-02-16 08:20 UTC, mchlkucera commented on SpectodaInterfaceLegacy.js
> +export const CONNECTOR_DEFAULT_VALUE = null;
👆 Connector default value je "default" ne? Bavíme se o "konektoru" jak je webbluetooth, simulated, atp.? Vubec nerozumim tomuto

2024-02-16 08:48 UTC, mchlkucera commented
In conclusion za mě hlavně nerozumim tomu co je CONNECTOR_DEFAULT_VALUE a proč má defaultně null value a nahradil bych magic čísla 7000, 5000 za něco smysluplného jako BEFORE_CONNECT_TIMEOUT - když budou nadefinované na jednom místě tak se s tím bude i do budoucna lépe pracovat imo

2024-02-16 08:55 UTC, mchlkucera requested changes

2024-02-16 08:55 UTC, mchlkucera commented on FlutterConnector.js
>      //   });
Pls remove

2024-02-16 08:55 UTC, mchlkucera commented on FlutterConnector.js
>      //   });
Commented out code

2024-02-16 08:55 UTC, mchlkucera commented on FlutterConnector.js
>        // throw(message, "Error: TC response timeouted");
💃💃💃

2024-02-16 08:55 UTC, mchlkucera commented on FlutterConnector.js
> +    if (timeout_number === CONNECTOR_DEFAULT_VALUE) { timeout_number = 5000; }
Proč zrovna tyhle čísla? Za mě porušuje no-magic-numbers rule

2024-02-16 08:55 UTC, mchlkucera commented on TimeTrack.js
>    }
Kudos za odstranění komentářů

2024-02-16 08:55 UTC, mchlkucera commented on SpectodaWebBluetoothConnector.js
>    // transmit() tryes to transmit data NOW. ASAP. It will fail,
tries 😛

2024-02-16 08:55 UTC, mchlkucera commented on SpectodaWebBluetoothConnector.js
>          });
Nebyl by zde lepší pattern
`
await ...
await ...
await ...
`
?

2024-02-16 08:55 UTC, mchlkucera commented on SpectodaWebBluetoothConnector.js
> +      }, timeout < 5000 ? 5000 : timeout);
no-magic-number, jedno číslo inicializované několikrát místo proměnné

2024-02-16 13:01 UTC, immakermatty commented on FlutterConnector.js
>      //   });
Ano.. Ale bolí mě to. Vubec z toho nemám dobrý pocit

2024-02-16 13:07 UTC, immakermatty commented on FlutterConnector.js
> +    if (timeout_number === CONNECTOR_DEFAULT_VALUE) { timeout_number = 5000; }
Protože z testování na starém Androidu, iPhone 13, iPhone SE, Spectoda Connectu na Macu a tvem Androidu vždy do cca 2s telefon najde Controller v okolí. A nemá smysl aby to timeoutovalo až po 10s - zbytečně to prodlužuje cely připojovací flow.

Já mám rád, když je to napsané ve funkci, na kterou je to naladěno. V tomto případě jen a pouze pro `autoSelect`. A magic number to není, protože přesne vidíš co to je - je to defaultní `scan_period_number` a defaultní `timeout_number` pro funkci `autoSelect`. 

Timeouty nejsou společné mezi connectorama ani mezi jetnotlivýma funkcema.

2024-02-16 13:14 UTC, immakermatty commented on SpectodaInterfaceLegacy.js
> +export const CONNECTOR_DEFAULT_VALUE = null;
Jde o to, že potřebuji způsob, který ve chvíli, kdy nenastavíš ve Spectoda.js connectTimeout, nebo scanDuration nebo jakykoli jiny timeout, tak chci aby connector nastavil defaultní hodnotu, která je vhodná pro ten daný connector. 

A tím, jak funguje logika function callů, které se ve SpectodaInterfaceLegacy.js dávají do fronty, tak pak se ty parametry volají s hodnotou, proto connect(timeout=10000) nefunguje a proto tímto říkám, že když je timeout===null, tak pak nastav defaultní hodnotu 10000.

Chapu, že to dela confusion, je to věc, která má zůstat čistě uvnitř Spectoda-js, do appky se tohle  CONNECTOR_DEFAULT_VALUE vubec nema dostat. Přemyslím, jak to udělat líp

2024-02-16 13:17 UTC, immakermatty commented on SpectodaWebBluetoothConnector.js
>          });
Já se vlastně hrozně štítím async funkcí protože nevím jak se to přesně chová v kombinaci s Promisama, tak se snažím mít maximum věcí synchronní Promisy

2024-02-16 13:23 UTC, immakermatty commented on SpectodaWebBluetoothConnector.js
> +      }, timeout < 5000 ? 5000 : timeout);
Vracím se zpátky k tomu, že si myslím, že ve chvíli kdy se jedná o timeout přímo určený pro jeden usecase v jedné funkci, tak si nemyslím, že je cokoli urychlující aby to bylo řešené přes balast constant které musíš hledat v nějakém speciálním souboru. Prostě tady vidím, při testování, že mi to timeoutuje dřív než má, měním pouze tohle číslo na přestě tomto místě a jsem si jistý, že tím měním pouze tohle číslo a ne taky někde v nějaké jiné funkci.

Co se týče toho, že je to nadefinované dvakrát - ano, to je valid point, tam bych rád našel v JS něco ala math::max(5000, timeout), ale aby to říkalo "timeout musí být aspoň 5000ms a pokud není tak použij 5000ms"

2024-02-16 13:30 UTC, immakermatty commented on SpectodaWebSerialConnector.js
> +    if (timeout === CONNECTOR_DEFAULT_VALUE) { timeout = 10000; }
Já jsem mega fanda connect(timeout = 10000), proto to tak bylo. Ale pak nefunguje logika stackování function callů, která je nadefinovaná ve SpectodaInterfaceLegacy.js, kde se dávají do fronty promisy ve chvíli kdy člověk spamuje funkce.

Ono to je totiž tak, že appka zavola ve Spectoda.js funkci connect(), která řekne interfacu, že se chce connect(), což tomu správnému connectoru ve chvíli kdy na něm neprobíhá žádná jiná funkce zavolá connect(), kde potřebuju aby když Spectoda.js nenadefinoval timeout (tzn, že je timeout rovno null), tak aby se použil defaultní timeout pro daný connector. Protože mít defaultní timeout na urovni Spectoda.js nebo SpectodaInterface pro vsechny connectory stejně jsem zjistil, že nedává smysl.

Takže pokud mi poradíte, jak udělat variabilní argumenty ve SpectodaInterfaceLegacy.js tak aby fungovalo v connectoru connect(timeout = 10000), tak to pojďme udělat takhle. Ale to znamená, že se musí uplně přepsat celá logika v SpectodaInterfaceLegacy.js. Proto bych to nechal takhle jak to je, ale nějak rozumně to vysvětlím, proč to tak je - což uplně nevím jak vysvětlit. Uživatelé spectoda-js vubec s CONNECTOR_DEFAULT_VALUE neprichazi do stiku

2024-02-16 13:30 UTC, immakermatty commented on TimeTrack.js
>    }
Tady tohle byl garbage co tam nemel uz co delat

2024-02-17 11:34 UTC, merged